### ISSUE TITLE
Avatar conversion from webp to png failed

### ISSUE THREAD

**Issue by lazaroblanc** [lazaroblanc/discord-bot#9]
Log:

```
Talk in channel Lounge (734383009683341383) ended with 2 participants
"e5c17884c8fd7cd9492551b248a82305.webp" -o "e5c17884c8fd7cd9492551b248a82305.png"
"522c9c41c4c841fcc4d0c30dc456b219.webp" -o "522c9c41c4c841fcc4d0c30dc456b219.png"
Error: Command failed: "/home/lazaro/kim/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp" "e5c17884c8fd7cd9492551b248a82305.webp" -o "e5c17884c8fd7cd9492551b248a82305.png"
Could not read 0 bytes of data from file e5c17884c8fd7cd9492551b248a82305.webp

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 255,
  signal: null,
  cmd: '"/home/lazaro/kim/node_modules/webp-converter/bin/libwebp_linux/bin/dwebp" "e5c17884c8fd7cd9492551b248a82305.webp" -o "e5c17884c8fd7cd9492551b248a82305.png"'
}
Drawing avatar for Sellmann to carousell image
Writing carousell image to disk
Creating talk ended embed
Posting talk ended embed
```

**Comment by lazaroblanc** [comment]
My guess is that the download fails so I've reenabled logging messages for the download function for now and will continue to monitor this.

**Comment by lazaroblanc** [comment]
Up until now, I've only been testing with 2 users (one with default, one with custom avatar). In this case both users had custom avatars. I've checked out the previous commit and did further testing with 2 users with customs avatars and can't reproduce the issue. Maybe the dwebp binary behaves differently on Linux than on Windows. will continue to monitor this.
My other guess is that the event "end" from the axios response was not precise enough. I've removed axios and switched back to the https module and am listening to the "close" event on the file.

**Comment by lazaroblanc** [comment]
I've now tested it with two custom avatars running on Linux instead of Windows and still can't reproduce the bug.
Waiting to see if the bug reappears with the same users on the other guild where the bug originally happened. If it doesn't I will close this issue for now.

**Comment by lazaroblanc** [comment]
> My other guess is that the event "end" from the axios response was not precise enough. I've removed axios and switched back to the https module and am listening to the "close" event on the file.

This seems to have fixed the problem.
